### PR TITLE
Fix PR check action

### PR DESCRIPTION
**Pull request by frank-bee**

### CODE REVIEW

**Comment by frank-bee** [comment]
@fbufler any idea why linter fails here?

**Comment by frank-bee** [comment]
tests also fail https://github.com/B-S-F/onyx/actions/runs/11037206144/job/30657500167

**Comment by fbufler** [comment]
> @fbufler any idea why linter fails here?

So something has to be different than in the other onyx repo, as linting works there just fine.
I also get a lot of errors in vscode when opening this repo:

Screenshot 2024-09-26 at 08 40 19

This is how it looks in the real onyx repo (just some information regarding spelling)
Screenshot 2024-09-26 at 08 40 03

**Comment by frank-bee** [comment]
@fbufler can you review this?
I tested all steps ... 2 remarks
- lint fails  but I have set it to continue in error
- for uploading the gist I had to use a PAT with my private account

**Review by fbufler — APPROVED** [review]
Basically LGTM
regarding your remarks:
1. I'm still a bit unsure why the lint does not work, as it works in the real respository where we sync from.
2. Do we need to upload the data to the gist? we also could just remove it.

**Comment by frank-bee** [comment]
1.  I will check this on monday

**Comment by frank-bee** [comment]
2. for now it is ok but jap we can remove this later

**Pull request merged**
